
import com.biomatters.geneious.publicapi.implementations.sequence.DefaultNucleotideSequence;
import org.apache.http.Consts;
import org.apache.http.HttpEntity;
import org.apache.http.HttpResponse;
import org.apache.http.NameValuePair;
import org.apache.http.client.ClientProtocolException;
import org.apache.http.client.ResponseHandler;
import org.apache.http.client.entity.UrlEncodedFormEntity;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.util.EntityUtils;
import org.junit.Test;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

@SuppressWarnings({"ImplicitNumericConversion", "HardcodedFileSeparator", "ClassHasNoToStringMethod"})
public class BrowserTest {
    private final String USER_AGENT = "Mozilla/5.0";




    @Test
    public void test1() throws Exception {

        DefaultNucleotideSequence chimera = new DefaultNucleotideSequence("Opt256_2_388", "ATGGCTGCCGATGGTTATCTTCCAGATTGGCTCGAGGACAACCTCTCTGAAGGCATTCGCGAGTGGTGGGACTTGAAACCTGGA-CCACCGCCACCCAAACCCG-CAGAGCGGCATAAGGACGACGGC-CGGGGTCTTGTGCTTCCTGGTTACAAGTACCTCGGACCCTTCAACGGACTCGACAAGGGGGAGCCCGTCAACGAGGCGGACGCAGCGGCCCTCGAGCACGACATCTCGTACAACGAGCAGCTCGA-GGCGGGTGACAACCCGTACCTCAAGTACAACCACGCCGACGCCGAGTTTCAGGAGAAGCTGGCCGACGATACGTCTTTTGGGGGCAACCTCGGGAAGGCAGTCTTCCAGGCCAAGAAGAGGGTTCTCGAACCTTTTGGTCTGGTTGAGGAACCTGTTAAGACGGCTCCTGGAAAGAAGCGTCCGGTA-GAGCAGTCTCCACAGGAGCCAGACTCCTCCTCGGGCATCGGCAAGACAGGCCAGCAGCCCGCTAAAAAGAGACTCAATTTTGGTCAGAC-TGGCGACGCAGACTCAGTCCCCGACCCTCAACCTCTCGGACAGCCTCCAGCA--GCCC-CCTCTGGTTTGGGAACTAATACAATGGCTTCAGGCGGTGGCG-CACCAATGG-CAGACAATAACGAAGGCGCCGACGGAGTGGGTAATTCCTCGGGAAATTGGCATTGCGATTCCACATGGATGGGCGACAGAGTCGTCACCAAGAGCACCCGAACCTGGGTCCTGCCCAGCTACAACAACCACCTCTAC-AAGCAAATCTCCAGT-GCTTCAA-CGGGAGCCAGCAACGACAAC-CACTACTTCGGCTACAGCACCCCCTGGGGGTATTTTGACTTCAACAGATTCCACTGCCACTTCTCACCACGTGACTGGCAGCGACTCATCAACAACAACTGGGGATTCCGGCCCAAGAGACTCAACTTCAAGCTCTTCAACATCCAAGTCAAGGAGGTCACGCA-GAATGATGGCACGACGACCATCGCCAATAACCTTACCAGCACGGTTCAAGTGTTTACGGACT-CGGAGTACCAGCTCCCGTACGTCGTCGGCAACG-GTACCGAGGGCTGCCTCCCTGCC-TTCCCGCCGCAGGTCTTCACGCTGCCGCAGTACGGCTACGCGACGCTCAACCGCGACAACACAGAAAATCCCACTGAG-CGCTCATCCTTTTTCTGCCTGGAATACTTCCCTTCGCAGATGCTGAGAACGGGCAACAACTTTACCTTCAGC-TACACCTTTGAGGACGTGCCTTTCCACAGCAGCTACGCTCACAGCCAGAGCCTGGACCGGCTGATGAATCCTCTCATCGACCAGTACCTGTACTACCT-GAACAGAACTCAA-AAT-CAGTCCGGAAGTGCC--CAAAA-CAAGGACTTGCTGTTTAGCCGTGGGTCTC--CTGCTGGCATGTCTGT-TCAGCCCAAAAACTGGCTACCTGGACCC-TGTTACCGG-CAGCAGCGCGTTTCAA---AGACAAAAACAGACAACAACAACAGCG--AATAC-T-CGTGGACTGGTGCTACCAAATATCATCTCAATGGCCGTGACTCTCT-GGTGAATCCT-GGCCCGGCTATGGCCTCACACAAAGACGACGAAGAAA--AGTTCTT-T-CCC-ATGAGCGGTGTCATGATTTTTGGCAAAGAG--AGCG--CCGGAGCTT-CAAACACTG--CAT-T---GGACAATGT-CATGATTACCGACGAAGAG-GAAATTAAAGCCACT-AACCCTGTGGCC-ACGGAG-AGATTTGGGACTG-TGGCAGTCAACCTCCAGAGCAGCAGCACAGAC--CCTGCGACCGGAGATGT-CCATGT-TATGGGAGCCTTACCTGGCATG-GTGTGGCA-AGACAGAGACGTGTACCTGCAGGGTCCCATTTGGGCCAAGATTCCTCACACGGATGG-ACACTTTCACCCGTCTCCG-CTGATGGGCGGCTTTGGACTGAAACACCCGCCTCCTCA-GATCCTCATCAAAAACACGCCTGTACCTG-GAAATAT-C-ACCAGCTTCAGCGACGTGCCG-GTAAGCT-CATTCATCACCCAGTACTCCACTGGACAGGTCACCGTGGAGATGGAGTGGGAGCTGAAGAAGGAAAACAGCAAGCGCTGGAATCCCGAGATCCAGTACACAAACAACTACAACGACCCCCAGTT--TGTGGACTTTGCTCCCGACAGCACCGGAGAATATAG-AACCACCCGCCCCATTGGCACCCGTTACCTCACCCGTCCCCTGTAA");
        ArrayList<DefaultNucleotideSequence> parentalSequence = new ArrayList<>();
        parentalSequence.add(new DefaultNucleotideSequence("aav2 opt", "ATGGCTGCCGATGGTTATCTTCCAGATTGGCTCGAGGACACTCTCTCTGAAGGCATTCGCCAGTGGTGGAAGTTGAAACCTGGA-CCACCGCCACCCAAACCCG-CAGAGCGGCATAAGGACGACAGC-CGGGGTCTTGTGCTTCCTGGTTACAAGTACCTCGGACCCTTCAACGGACTCGACAAGGGGGAGCCCGTCAACGAGGCGGACGCAGCGGCCCTCGAGCACGACAAGGCCTACGACCGGCAGCTCGACAGCGG-TGACAACCCGTACCTCAAGTACAACCACGCCGACGCCGAGTTTCAGGAGCGTCTGAAAGAAGATACGTCTTTTGGGGGCAACCTCGGGCGAGCAGTCTTCCAGGCCAAGAAGAGGGTTCTCGAACCTCTTGGTCTGGTTGAGGAACCTGTTAAGACGGCTCCTGGAAAGAAGCGTCCGGTA-GAGCACTCTCCAGTGGAGCCAGACTCCTCCTCGGGCACCGGCAAGGCGGGCCAGCAGCCCGCTAGAAAGAGACTCAATTTTGGTCAGAC-TGGCGACGCAGACTCAGTCCCCGACCCTCAACCTCTCGGACAGCCTCCAGCA--GCCC-CCTCTGGTTTGGGAACTAATACAATGGCTACAGGCAGTGGCG-CACCAATGG-CAGACAATAACGAAGGCGCCGACGGAGTGGGTAATTCCTCGGGAAATTGGCATTGCGATTCCACATGGATGGGCGACAGAGTCATCACCACCAGCACCCGAACCTGGGCCCTGCCCACCTACAACAACCACCTCTAC-AAGCAAATC---AGTAGC--CAATCAGGAGCCAGCAACGACAAC-CACTACTTCGGCTACAGCACCCCCTGGGGGTATTTTGACTTCAACAGATTCCACTGCCACTTCTCACCACGTGACTGGCAGCGACTCATCAACAACAACTGGGGATTCCGGCCCAAGAGACTCAACTTCAAGCTCTTCAACATCCAAGTCAAGGAGGTCACGCA-GAATGATGGCACGACGACCATCGCCAATAACCTTACCAGCACGGTTCAAGTGTTTACGGACT-CGGAGTACCAGCTCCCGTACGTCCTCGGCTCTGCGCACC-AGGGCTGCCTCCCT-CCGTTCCCGGCGGACGTCTTCATGGTGCCGCAGTACGGCTACCTGACGCTGAACAACGGCAGC-CAGG-----CCG-TGGGACGCTCATCCTTTTACTGCCTGGAATACTTCCCTTCGCAGATGCTGAGAACGGGCAACAACTTTACCTTCAGC-TACACCTTTGAGGACGTGCCTTTCCACAGCAGCTACGCTCACAGCCAGAGCCTGGACCGGCTGATGAATCCTCTCATCGACCAGTACCTGTACTACCT-GAGCAGAACT-AACACT-CCATCCGGAACCACCA-CGCAATCAAGG--TTGCAGTTTAGCCA--GGCCGGAGCGAGTGACAT-TCGGGACCAGTCTAGAAACTGGCTACCTGGACCC-TGTTACCGG-CAGCAGCGCGTTTCAA---AGACATCTGCGGACAACAACAACAGCG--AATAC-T-CGTGGACTGGTGCTACCAAATATCATCTCAATGGCCGTGACTCTCT-GGTGAATCCT-GGCCCGGCTATGGCCTCACACAAAGACGACGAAGAAA--AGTTCTT-T-CCCCA-GAGCGGTGTCCTCATTTTTGGCAAACAA--GGC---TCAGAGAAAACAAACGTGG-ATAT-T---GAA-AAGGT-CATGATTACCGACGAAGAG-GAAATTAGGACCACT-AACCCTGTGGCC-ACGGAGCAG-TATGGGTCTG-TGTCTACCAACCTCCAGAGAGGCA--ACAGACAAGCAGCGACCGCAGATGT-CAACACACA-GGGAGTTTTACCTGGCATG-GTGTGGCA-AGACAGAGACGTGTACCTGCAGGGTCCCATTTGGGCCAAGATTCCTCACACGGATGG-ACACTTTCACCCGTCTCCG-CTGATGGGCGGCTTTGGACTGAAACACCCGCCTCCTCA-GATCCTCATCAAAAACACGCCTGTACCTGCGAATCCTTCGACCACCTTCAGCG-C-TGCAAAGTTTGCTTCATTCATCACCCAGTACTCCACTGGACAGGTCAGCGTGGAGATTGAGTGGGAGCTGCAGAAGGAAAACAGCAAGCGCTGGAATCCCGAGATCCAGTACACATCCAACTACAACAAA-TCT-GTTAATGTGGACTTTACTGTGGACACTAATGGAGTGTATAGTGAGC-CTCGCCCCATTGGCACCCGTTACCTCACCCGTAATCTGTAA"));
        parentalSequence.add(new DefaultNucleotideSequence("aav5 opt", "ATGTCTTTTGTTGATCACCCTCCAGATTGGCTCGAGGA-AGT-TGG-TGAAGGCCTTCGCGAGTTTTTGGGCTTGGAAGCGGGA-CCACCGAAACCCAAACCCAACC-AGCAACATCAGGACCA-AGCTCGGGGTCTTGTGCTTCCTGGTTACAACTACCTCGGACCCGGCAACGGACTCGACCGAGGGGAGCCCGTCAACAGGGCGGACGAGGTCGCCCGAGAGCACGACATCTCGTACAACGAGCAGCTCGA-GGCGGGTGACAACCCGTACCTCAAGTACAACCACGCCGACGCCGAGTTTCAGGAGAAGCTGGCCGACGATACGTCTTTTGGGGGCAACCTCGGGAAGGCAGTCTTCCAGGCCAAGAAGAGGGTTCTCGAACCTTTTGGTCTGGTTGAGGAAGGCGCTAAGACGGCTCCTACCGGAAAGCGTATAG-ACGATCACTTTCCA-AAAAGAAAGAAGGCT---CGG--ACCG--AAGA--GG--A----CTC-C----AAGCC-CTCCACCTCG-TCAGACGCAGAGGC-TGGACCCAG---CGGATCC-CAGCAGCT-GCAGA-TC-CCAGCACAACCCGCCTCTAGTTTGGGAGCTGATACAATGTCTGCAGGCGGTGGCGGC-CCATTGGGC-GACAATAACCAAGGCGCCGACGGAGTGGGTAATGCCTCGGGAGATTGGCATTGCGATTCCACATGGATGGGCGACAGAGTCGTCACCAAGAGCACCCGAACCTGGGTCCTGCCCAGCTACAACAACCACCAGTACCGAG-AGATCAAAAGTGGCT-CAGTCGACGGA-AGCAACGCCAACGC-CTACTTCGGCTACAGCACCCCCTGGGGGTATTTTGACTTCAACAGATTCCACAGCCACTGGTCACCACGTGACTGGCAGCGACTCATCAACAACTACTGGGGATTCCGGCCCCGGTCCCTCCGGGTCAAGATCTTCAACATCCAAGTCAAGGAGGTCACG-GTGCAGGATTCCACGACGACCATCGCCAATAACCTTACCAGCACGGTTCAAGTGTTTACGGACGACG-ACTACCAGCTCCCGTACGTCGTCGGCAACG-GTACCGAGGGCTGCCTCCCTGCC-TTCCCGCCGCAGGTCTTCACGCTGCCGCAGTACGGCTACGCGACGCTCAACCGCGACAACACAGAAAATCCCACTGAG-CGCTCATCCTTTTTCTGCCTGGAATACTTCCCTTCGAAGATGCTGAGAACGGGCAACAACTTTGAATTCA-CGTACAACTTTGAGGAAGTGCCTTTCCACAGCAGCTTCGCTCCCAGCCAGAACCTGTTCAAGCTGGCCAATCCTCTCGTGGACCAGTACCTGTACCGCTTCGTGTCGA-CT-AACAATACTGGC-GGA-GT-CCAGTTTAA-CAAGAACCTG--GC--GGG-G-AGAT--A--C-GCCAACAC--C----T-A--C-AAAAACTGGTTCCCTGGACCCATGG-GCCGGACC-CAG-G-GCTGGAACCTGGGC-TCTGGGGTCAACCGCGCCAGCGTCAGTGCCTTCGCC-AC-GAC-CAATAGGATG-GAGCTCGAGGGC-GCGAGTTACCAGGTGCCCCCTCAGC-CGA--ACGGCATGACG-AACAACCTCCAGGGCAGCAACACCTATGCCCTG-GAG-AACACTATGATTTTTAACAGCCAGCCGGCGAACCCGGGCA--CAACCGCAACGTACCTCGAGGGGAATATGC-TCATTACCAGCGAA-AGCGAAAC-GCAGCCGGTGAACCGCGTGGCCTACAACGTCG--GCGGG-CAGATGGCAACCAACAACCAGAGCAGCACCACAG-CT-CCTGCGACCGGA-ACTTACAACCTCCA-GGAAATCGTGCCTGGCA-GCGTGTGG-ATGGAGAGAGACGTGTACCTGCAGGGTCCCATTTGGGCCAAGATTCCTGAGACGGG-GGCGCACTTTCACCCGTCTCCGGCC-ATGGGCGGCTTTGGACTGAAACACCCGCCTCCT-ATGATGCTCATCAAAAACACGCCTGTACCTG-GAAATAT-C-ACCAGCTTCAGCGACGTGCCG-GTAAGCT-CATTCATCACCCAGTACTCCACTGGACAGGTCACCGTGGAGATGGAGTGGGAGCTGAAGAAGGAAAACAGCAAGCGCTGGAATCCCGAGATCCAGTACACAAACAACTACAACGACCCCCAGTT--TGTGGACTTTGCTCCCGACAGCACCGGAGAATATAG-AACCACCCGCCCCATTGGCACCCGTTACCTCACCCGTCCCCTGTAA"));
        parentalSequence.add(new DefaultNucleotideSequence("aav6 opt", "ATGGCTGCCGATGGTTATCTTCCAGATTGGCTCGAGGACAACCTCTCTGAAGGCATTCGCGAGTGGTGGGACTTGAAACCTGGAGCC-CCGAAACCCAAAGCCAACC-AGCAAAAGCAGGACGACGGC-CGGGGTCTTGTGCTTCCTGGTTACAAGTACCTCGGACCCTTCAACGGACTCGACAAGGGGGAGCCCGTCAACGCGGCGGACGCAGCGGCCCTCGAGCACGACAAGGCCTACGACCAGCAGCTCAA-GGCGGGTGACAACCCGTACCTCCGGTACAACCACGCCGACGCCGAGTTTCAGGAGCGTCTGCAAGAAGATACGTCTTTTGGGGGCAACCTCGGGCGAGCAGTCTTCCAGGCCAAGAAGAGGGTTCTCGAACCTTTTGGTCTGGTTGAGGAAGGCGCTAAGACGGCTCCTGGAAAGAAGCGTCCGGTA-GAGCAGTCTCCACAGGAGCCAGACTCCTCCTCGGGCATCGGCAAGACAGGCCAGCAGCCCGCTAAAAAGAGACTCAATTTTGGTCAGAC-TGGCGACTCAGAGTCAGTCCCCGACCCTCAACCTCTCGGAGAACCTCCAGCA--ACCC-CCGCTGCTGTGGGACCTACTACAATGGCTTCAGGCGGTGGCG-CACCAATGG-CAGACAATAACGAAGGCGCCGACGGAGTGGGTAATGCCTCGGGAAATTGGCATTGCGATTCCACATGGCTGGGCGACAGAGTCATCACCACCAGCACCCGAACCTGGGCCCTGCCCACCTACAACAACCACCTCTAC-AAGCAAATCTCCAGT-GCTTCAA-CGGGAGCCAGCAACGACAAC-CACTACTTCGGCTACAGCACCCCCTGGGGGTATTTTGACTTCAACAGATTCCACTGCCACTTCTCACCACGTGACTGGCAGCGACTCATCAACAACAACTGGGGATTCCGGCCCAAGAGACTCAACTTCAAGCTCTTCAACATCCAAGTCAAGGAGGTCACG-ACGAATGATGGCGTCACGACCATCGCCAATAACCTTACCAGCACGGTTCAAGTGTTTTCGGACT-CGGAGTACCAGCTCCCGTACGTCCTCGGCTCTGCGCACC-AGGGCTGCCTCCCT-CCGTTCCCGGCGGACGTCTTCATGATTCCGCAGTACGGCTACCTGACGCTGAACAACGGCAGC-CAGG-----CCG-TGGGACGCTCATCCTTTTACTGCCTGGAATACTTCCCTTCGCAGATGCTGAGAACGGGCAACAACTTTACCTTCAGC-TACACCTTTGAGGACGTGCCTTTCCACAGCAGCTACGCTCACAGCCAGAGCCTGGACCGGCTGATGAATCCTCTCATCGACCAGTACCTGTACTACCT-GAACAGAACTCAA-AAT-CAGTCCGGAAGTGCC--CAAAA-CAAGGACTTGCTGTTTAGCCGTGGGTCTC--CTGCTGGCATGTCTGT-TCAGCCCAAAAACTGGCTACCTGGACCC-TGTTACCGG-CAGCAGCGCGTTTCAA---AGACAAAAACAGACAACAACAACAGC---AACTT-TACCTGGACTGGTGCTTCAAAATATAACCTCAATGGCCGTGAATCTAT-CATCAATCCT-GGCACTGCTATGGCCTCACACAAAGACGACAAAGACA--AGTTCTT-T-CCC-ATGAGCGGTGTCATGATTTTTGGCAAAGAG--AGCG--CCGGAGCTT-CAAACACTG--CAT-T---GGACAATGT-CATGATTACCGACGAAGAG-GAAATTAAAGCCACT-AACCCTGTGGCC-ACGGAG-AGATTTGGGACTG-TGGCAGTCAACCTCCAGAGCAGCAGCACAGAC--CCTGCGACCGGAGATGT-CCATGT-TATGGGAGCCTTACCTGGCATG-GTGTGGCA-AGACAGAGACGTGTACCTGCAGGGTCCCATTTGGGCCAAGATTCCTCACACGGATGG-ACACTTTCACCCGTCTCCG-CTGATGGGCGGCTTTGGACTGAAACACCCGCCTCCTCA-GATCCTCATCAAAAACACGCCTGTACCTGCGAATCCTCCGGCGGAGTTCAGCG-C-TACAAAGTTTGCTTCATTCATCACCCAGTACTCCACTGGACAGGTCAGCGTGGAGATTGAGTGGGAGCTGCAGAAGGAAAACAGCAAGCGCTGGAATCCCGAGGTGCAGTACACATCCAACTACG-CAAAATCT-GCCAATGTGGACTTTACTGTGGACAACAATGGACTTTATACTGAGC-CTCGCCCCATTGGCACCCGTTACCTCACCCGTCCCCTGTAA"));

        List<NameValuePair> formparams = new ArrayList<NameValuePair>();
        formparams.add(new BasicNameValuePair("ParentsSeqs", "value1"));
        formparams.add(new BasicNameValuePair("MutantsSeqs", "value2"));
        UrlEncodedFormEntity entity = new UrlEncodedFormEntity(formparams, Consts.UTF_8);
        HttpPost httppost = new HttpPost("http://qpmf.rx.umaryland.edu/doXOver");
        httppost.setEntity(entity);
        CloseableHttpClient httpclient = HttpClients.createDefault();
        try {
            //HttpGet httpget = new HttpGet("http://qpmf.rx.umaryland.edu/Xover.html");

            System.out.println("Executing request " + httppost.getRequestLine());

            // Create a custom response handler
            ResponseHandler<String> responseHandler = new ResponseHandler<String>() {

                @Override
                public String handleResponse( HttpResponse response) throws ClientProtocolException, IOException {
                    int status = response.getStatusLine().getStatusCode();
                    if (status >= 200 && status < 300) {
                        HttpEntity entity = response.getEntity();
                        return entity != null ? EntityUtils.toString(entity) : null;
                    } else {
                        throw new ClientProtocolException("Unexpected response status: " + status);
                    }
                }

            };
            String responseBody = httpclient.execute(httppost, responseHandler);
            System.out.println("----------------------------------------");
            System.out.println(responseBody);
        } finally {
            httpclient.close();
        }
    }
}